### ISSUE TITLE
Project not run with ionic serve

### ISSUE THREAD

**Issue by villander** [ionicthemes/facebook-login-with-ionic-framework#7]
WARN: ionic.project has been renamed to ionic.config.json, please rename it.
There is an error in your gulpfile: 
Error: `libsass` bindings not found. Try reinstalling `node-sass`?
    at getBinding (/Users/flama/Projects/facebook-login-with-ionic-framework/node_modules/node-sass/lib/index.js:22:11)
    at Object.<anonymous> (/Users/flama/Projects/facebook-login-with-ionic-framework/node_modules/node-sass/lib/index.js:188:23)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/flama/Projects/facebook-login-with-ionic-framework/node_modules/gulp-sass/index.js:3:17)
    at Module._compile (module.js:434:26)

**Comment by djabif** [comment]
You can solve lib-sass issue doing this:
1. Open to package.json
2. Change “gulpsass”: “1.3.3” to “gulpsass”: “2.0.4”
3. Delete node modules folder
4. Run npm install

**Comment by villander** [comment]
Thanks @djabif its work for me!
